"""Verify a built sdist contains only files tracked in git.

A source distribution is assembled from the working directory, so anything
sitting there untracked — editor state, local tooling directories, scratch
notes — is a candidate for publication. A published version number cannot
be withdrawn and reused, so this runs before upload rather than after.

Usage:
    python scripts/check_sdist.py [dist/]

Exits non-zero and prints the offending paths if the sdist contains
anything git does not track.
"""

from __future__ import annotations

import subprocess
import sys
import tarfile
from pathlib import Path

# Generated by the build backend, never present in the repository.
ALLOWED_UNTRACKED = {"PKG-INFO"}


def tracked_files() -> set[str]:
    """Every path git tracks, as posix-style relative paths."""
    result = subprocess.run(
        ["git", "ls-files"],
        capture_output=True,
        text=True,
        check=True,
    )
    return {line.strip() for line in result.stdout.splitlines() if line.strip()}


def sdist_files(archive: Path) -> set[str]:
    """Paths inside the sdist, with the top-level version directory stripped."""
    names: set[str] = set()
    with tarfile.open(archive, "r:gz") as tar:
        for member in tar.getmembers():
            if not member.isfile():
                continue
            _, _, relative = member.name.partition("/")
            if relative:
                names.add(relative)
    return names


def find_sdist(dist_dir: Path) -> Path:
    archives = sorted(dist_dir.glob("*.tar.gz"))
    if not archives:
        raise SystemExit(f"no sdist found in {dist_dir} — run `hatch build` first")
    if len(archives) > 1:
        raise SystemExit(
            f"multiple sdists in {dist_dir}; remove stale builds so the check is unambiguous:\n"
            + "\n".join(f"  {a.name}" for a in archives)
        )
    return archives[0]


def main() -> int:
    dist_dir = Path(sys.argv[1] if len(sys.argv) > 1 else "dist")
    archive = find_sdist(dist_dir)

    extras = sorted(sdist_files(archive) - tracked_files() - ALLOWED_UNTRACKED)
    if extras:
        print(f"{archive.name} contains {len(extras)} file(s) not tracked in git:\n")
        for path in extras:
            print(f"  {path}")
        print(
            "\nAdd them to [tool.hatch.build.targets.sdist] exclude in pyproject.toml,"
            "\nor commit them if they belong in the distribution."
        )
        return 1

    print(f"{archive.name}: clean - every file is tracked in git")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
